# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aizenk.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, ):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 352)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect( 50, 5, 1100, 111))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(24)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")


        def start_aq(self):
            subprocess.run(["python", "q.py"])
        
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(500, 140, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(18)
        font.setItalic(True)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.start.clicked.connect(start_aq)

        def det (self):
            subprocess.run(["python", "det.py"])

        self.det = QtWidgets.QPushButton(self.centralwidget)
        self.det.setGeometry(QtCore.QRect(500, 250, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(18)
        font.setItalic(True)
        self.det.setFont(font)
        self.det.setObjectName("det")
        self.det.clicked.connect(det)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "тест айзенка на визначення типу темпераменту"))
        self.start.setText(_translate("MainWindow", "почати"))
        self.det.setText(_translate("MainWindow", "деталі"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
