# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choleric.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
  #налаштування вікна
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 600)
        Dialog.setStyleSheet("background-color: rgb(221, 184, 125);")
 #текст з написом холерик
        self.choleric = QtWidgets
        self.choleric = QtWidgets.QLabel(Dialog)
        self.choleric.setGeometry(QtCore.QRect(50, 9, 900, 100))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(24)
        self.choleric.setFont(font)
        self.choleric.setObjectName("choleric")
        self.choleric_desc = QtWidgets.QLabel(Dialog)
        self.choleric_desc.setGeometry(QtCore.QRect(50,100, 800, 500))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(16)
        self.choleric_desc.setFont(font)
        self.choleric_desc.setObjectName("choleric_desc")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.choleric.setText(_translate("Dialog", "Холерик"))
        self.choleric_desc.setText(_translate("Dialog", "Тип темпераменту, який характеризується високою\n"
"активністю і швидкою реакцією.\n"
"Яскраво виражений екстраверт, якому складно\n"
"стримувати свої почуття. Енергійний, але\n"
"не відрізняється стриманістю, запальний,\n"
"може різко змінювати свій емоційний стан.\n"
"Холерик може проявляти високу працездатність,\n"
"але зазвичай його поривів\n"
"вистачає ненадовго, а високий рівень активності\n"
"на старті, призводить до швидкого виснаження."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
