# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'det.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1000, 65))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(24)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 65, 800, 100))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 110, 500, 200))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        
        self.choleric = QtWidgets.QGraphicsView(self.centralwidget)
        self.choleric.setGeometry(QtCore.QRect(380, 270, 171, 161))
        self.choleric.setStyleSheet("background-color: rgb(221, 154, 15);")
        self.choleric.setObjectName("choleric")
        
        self.phlegmatic = QtWidgets.QGraphicsView(self.centralwidget)
        self.phlegmatic.setGeometry(QtCore.QRect(210, 430, 171, 161))
        self.phlegmatic.setStyleSheet("background-color: rgb(113, 96, 136);")
        self.phlegmatic.setObjectName("phlegmatic")
        
        self.melancholic = QtWidgets.QGraphicsView(self.centralwidget)
        self.melancholic.setGeometry(QtCore.QRect(380, 430, 171, 161))
        self.melancholic.setStyleSheet("background-color: rgb(88, 195, 226);")
        self.melancholic.setObjectName("melancholic")

        def sanguine (self):
            subprocess.run(["python", "sanguine.py"])

        self.sanguine = QtWidgets.QGraphicsView(self.centralwidget)
        self.sanguine.setGeometry(QtCore.QRect(210, 270, 171, 161))
        self.sanguine.setStyleSheet("background-color: rgb(255, 237, 0);")
        self.sanguine.setObjectName("sanguine")

        self.sanguineButton = QtWidgets.QPushButton(self.centralwidget)
        self.sanguineButton.setGeometry(QtCore.QRect(220, 330, 150, 51))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.sanguineButton.setFont(font)
        self.sanguineButton.setStyleSheet("background-color: rgb(192, 255, 251);")
        self.sanguineButton.setObjectName("sanguineButton")
        self.sanguineButton.clicked.connect(sanguine)

        def melancholic (self):
            subprocess.run(["python", "melancholic.py"])

        self.melancholicButton = QtWidgets.QPushButton(self.centralwidget)
        self.melancholicButton.setGeometry(QtCore.QRect(390, 475, 150, 51))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.melancholicButton.setFont(font)
        self.melancholicButton.setStyleSheet("background-color: rgb(248, 255, 115);")
        self.melancholicButton.setObjectName("melancholicButton")
        self.melancholicButton.clicked.connect(melancholic)
        
        def choleric (self):
            subprocess.run(["python", "choleric.py"])
        
        self.cholericButton = QtWidgets.QPushButton(self.centralwidget)
        self.cholericButton.setGeometry(QtCore.QRect(390, 330, 150, 51))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.cholericButton.setFont(font)
        self.cholericButton.setStyleSheet("background-color: rgb(176, 160, 194);")
        self.cholericButton.setObjectName("cholericButton")
        self.cholericButton.clicked.connect(choleric)

        def phlegmatic():
            subprocess.run(["python", "phlegmatic.py"])
        self.phlegmaticButton = QtWidgets.QPushButton(self.centralwidget)
        self.phlegmaticButton.setGeometry(QtCore.QRect(220, 475, 150, 51))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.phlegmaticButton.setFont(font)
        self.phlegmaticButton.setStyleSheet("background-color: rgb(226, 186, 140);")
        self.phlegmaticButton.setObjectName("phlegmaticButton")
        self.phlegmaticButton.clicked.connect(phlegmatic)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Що таке тип темпераменту?"))
        self.label_2.setText(_translate("MainWindow", "Темперамент - головна властивість особистості. Його вважають найбільш стійкою характеристикою особистості людини, яка майже не змінюється впродовж життя і виявляється у всіх сферах життєдіяльності."))
        self.label_3.setText(_translate("MainWindow", "Загальновизнаним є виділення чотирьох типів темпераменту:"))
        self.sanguineButton.setText(_translate("MainWindow", "Сангвінік"))
        self.melancholicButton.setText(_translate("MainWindow", "Меланхолік"))
        self.cholericButton.setText(_translate("MainWindow", "Холерик"))
        self.phlegmaticButton.setText(_translate("MainWindow", "Флегматик"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
