# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'melancholic.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 500)
        Dialog.setStyleSheet("background-color: rgb(188, 223, 238);")
        self.Melancholic = QtWidgets.QLabel(Dialog)
        self.Melancholic.setGeometry(QtCore.QRect(10, 0, 255, 51))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(24)
        self.Melancholic.setFont(font)
        self.Melancholic.setObjectName("Melancholic")
        self.Melancholic_desc = QtWidgets.QLabel(Dialog)
        self.Melancholic_desc.setGeometry(QtCore.QRect(100, 60, 800, 400))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(16)
        self.Melancholic_desc.setFont(font)
        self.Melancholic_desc.setObjectName("Melancholic_desc")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Melancholic.setText(_translate("Dialog", "Меланхолік"))
        self.Melancholic_desc.setText(_translate("Dialog", "Чутливий, вразливий і ранимий тип темпераменту,\n"
" який найчастіше є вираженим інтровертом.\n"
" Може дуже гостро реагувати на різні зовнішнi\n"
" чинники, аж до того, що навіть незначний привід\n"
" може викликати в нього сльози і тривалу образу.\n"
"Як правило, не впевнений в своїх силах,\n"
" швидко може опускати руки в разі невдачі,\n"
" відрізняється боязкістю і підвищеною стомлюваністю."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
