# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phlegmatic.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 500)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(16)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(152, 126, 167);")
        
        self.Phlegmatic = QtWidgets.QLabel(Dialog)
        self.Phlegmatic.setGeometry(QtCore.QRect(0, 0, 250, 61))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(24)
        self.Phlegmatic.setFont(font)
        self.Phlegmatic.setObjectName("Phlegmatic")
        self.Phlegmatic.setStyleSheet("color: white")

        self.Phlegmatic_desc = QtWidgets.QLabel(Dialog)
        self.Phlegmatic_desc.setGeometry(QtCore.QRect(50, 50, 1000, 391))
        self.Phlegmatic_desc.setObjectName("Phlegmatic_desc")
        self.Phlegmatic_desc.setStyleSheet("color: white")
        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Phlegmatic.setText(_translate("Dialog", "Флегматик"))
        self.Phlegmatic_desc.setText(_translate("Dialog", "Найбільш спокійний і врівноважений тип темпераменту,\n"
" якого складно вивести з себе.\n"
" Зовні виглядає незворушною, скупою на прояв емоцій людиною,\n"
" для якої взаємодія з оточуючими людьми не має особливого значення.\n"
"В роботі відрізняється наполегливістю і завзятістю,\n"
" які в повній мірі компенсують йогo неспішний ритм.\n"
" Флегматик не боїться рутини, і часто є ідеальним виконавцем\n"
" для вирішення тривалих у часі, монотонних завдань."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
