# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sanguine.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 490)
        Dialog.setStyleSheet("background-color: rgb(255, 246, 176);")
        self.sanguine = QtWidgets.QLabel(Dialog)
        self.sanguine.setGeometry(QtCore.QRect(10, 10, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(24)
        self.sanguine.setFont(font)
        self.sanguine.setObjectName("sanguine")
        self.sanguine_desc = QtWidgets.QLabel(Dialog)
        self.sanguine_desc.setGeometry(QtCore.QRect(50, 60, 950, 500))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(16)
        self.sanguine_desc.setFont(font)
        self.sanguine_desc.setObjectName("sanguine_desc")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.sanguine.setText(_translate("Dialog", "Сангвінік"))
        self.sanguine_desc.setText(_translate("Dialog", "Активний і емоційний тип темпераменту. \n"
            "На відміну від холерика, має більш\n"
            "позитивні погляди на світ і настрій його переважно\n"
            "зі знаком плюс. \n"
            "Зазвичай швидко реагує на події, має жваву міміку.\n"
            "Легко перемикає увагу, але при цьому, може довго працювати\n"
            "над певним завданням, не втрачаючи фокусу.\n"
            "\n"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
